import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service - CharcuterME',
  description: 'Terms of service for CharcuterME - AI-powered girl dinner generator',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FAF9F7] py-12 px-6">
      <div className="max-w-2xl mx-auto">
        <Link
          href="/"
          className="text-[#A47864] hover:text-[#8B6B5D] text-sm mb-8 inline-block"
        >
          &larr; Back to app
        </Link>

        <h1 className="font-serif text-3xl text-[#5D4E45] mb-8">Terms of Service</h1>

        <div className="prose prose-stone max-w-none space-y-6 text-[#6B5B4F]">
          <p className="text-sm text-[#736B63]">
            Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>

          <section>
            <h2 className="text-xl font-serif text-[#5D4E45] mt-8 mb-4">Acceptance of Terms</h2>
            <p>
              By using CharcuterME, you agree to these terms. If you don&apos;t agree, please don&apos;t use the service.
              We may update these terms from time to time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#5D4E45] mt-8 mb-4">What CharcuterME Does</h2>
            <p>
              CharcuterME is an entertainment app that uses AI to generate funny names and images for your meals.
              It&apos;s meant to be fun and shareable. The AI-generated content is for entertainment purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#5D4E45] mt-8 mb-4">Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Use the service to generate harmful, offensive, or illegal content</li>
              <li>Attempt to manipulate or &quot;jailbreak&quot; the AI systems</li>
              <li>Upload photos containing inappropriate content</li>
              <li>Use the service in any way that violates applicable laws</li>
              <li>Attempt to reverse engineer, hack, or disrupt the service</li>
              <li>Use automated tools to access the service at scale</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#5D4E45] mt-8 mb-4">AI-Generated Content</h2>
            <p>
              Content generated by CharcuterME is created by AI and may be unpredictable.
              We do our best to ensure outputs are fun and appropriate, but we cannot guarantee
              every output will meet your expectations.
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>AI outputs are provided &quot;as is&quot; without warranties</li>
              <li>We are not responsible for how you use or share AI-generated content</li>
              <li>You should review content before sharing publicly</li>
              <li>We may filter or modify outputs to maintain quality</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#5D4E45] mt-8 mb-4">Content You Share</h2>
            <p>
              When you share CharcuterME content on social media or elsewhere:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>You are responsible for the content you share</li>
              <li>You grant us permission to use shared content for promotional purposes</li>
              <li>We may remove or disable content that violates these terms</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#5D4E45] mt-8 mb-4">Photos You Upload</h2>
            <p>
              For the vibe check feature, photos you upload are:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Sent to OpenAI for analysis and immediately discarded by us</li>
              <li>Subject to OpenAI&apos;s terms and privacy policy</li>
              <li>Your responsibility to ensure you have rights to upload</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#5D4E45] mt-8 mb-4">Disclaimers</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>CharcuterME is for entertainment only, not nutritional advice</li>
              <li>The service is provided &quot;as is&quot; without warranties of any kind</li>
              <li>We are not liable for any damages arising from use of the service</li>
              <li>Service availability is not guaranteed</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#5D4E45] mt-8 mb-4">Termination</h2>
            <p>
              We may suspend or terminate access to CharcuterME at any time, for any reason,
              without notice. This includes if we believe you have violated these terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#5D4E45] mt-8 mb-4">Report Issues</h2>
            <p>
              If you encounter inappropriate content or have concerns about the service,
              please contact us through our GitHub repository. We take reports seriously
              and will investigate promptly.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#5D4E45] mt-8 mb-4">Contact</h2>
            <p>
              Questions about these terms? Reach out through our GitHub repository.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-[#E8B4A0] flex gap-4">
          <Link
            href="/"
            className="text-[#A47864] hover:text-[#8B6B5D]"
          >
            &larr; Back to CharcuterME
          </Link>
          <span className="text-[#E8B4A0]">|</span>
          <Link
            href="/privacy"
            className="text-[#A47864] hover:text-[#8B6B5D]"
          >
            Privacy Policy
          </Link>
        </div>
      </div>
    </div>
  );
}
